In [89]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [90]:
import keras

In [91]:
import pandas as pd
import numpy as np

In [92]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [93]:
Vac_Train = pd.read_csv("/content/drive/My Drive/Colab Notebooks/NLP/vaccinate or not NLP zindi/Train.csv")

Vac_Test =pd.read_csv("/content/drive/My Drive/Colab Notebooks/NLP/vaccinate or not NLP zindi/Test.csv")


In [94]:
len(Vac_Train),len(Vac_Test)

(10001, 5177)

In [95]:
# Vac_Train.isnull().sum(),Vac_Test.isnull().sum()
Vac_Train.dropna(),Vac_Test.dropna()

(       tweet_id  ... agreement
 0      CL1KWCMY  ...  1.000000
 1      E3303EME  ...  1.000000
 2      M4IVFSMS  ...  1.000000
 3      1DR6ROZ4  ...  1.000000
 4      J77ENIIE  ...  1.000000
 ...         ...  ...       ...
 9996   IU0TIJDI  ...  1.000000
 9997   WKKPCJY6  ...  0.666667
 9998   ST3A265H  ...  1.000000
 9999   6Z27IJGD  ...  1.000000
 10000  P6190L3Q  ...  0.666667
 
 [9999 rows x 4 columns],
       tweet_id                                          safe_text
 0     00BHHHP1  <user> <user> ... &amp; 4 a vaccine given 2 he...
 1     00UNMD0E  Students starting school without whooping coug...
 2     01AXPTJF  I'm kinda over every ep of <user> being "rippe...
 3     01HOEQJW  How many innocent children die for lack of vac...
 4     01JUKMAO  CDC eyeing bird flu vaccine for humans, though...
 ...        ...                                                ...
 5172  ZXVVNC5O  jenny mccarthy is on new years rockin eve. wha...
 5173  ZYIANVI8  Measles reported in Clark Co. for 1

In [96]:
Xtrain = Vac_Train.drop('label',axis=1)
Ytrain = Vac_Train['label']

Xtest = Vac_Test['safe_text']

In [97]:
Xtrain.shape,Ytrain.shape,Xtest.shape

((10001, 3), (10001,), (5177,))

In [98]:
import tensorflow as tf

from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM

from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [99]:
Vocabulary_size = 5000

In [100]:
Vac_Train

tweet_id  ... agreement
0      CL1KWCMY  ...  1.000000
1      E3303EME  ...  1.000000
2      M4IVFSMS  ...  1.000000
3      1DR6ROZ4  ...  1.000000
4      J77ENIIE  ...  1.000000
...         ...  ...       ...
9996   IU0TIJDI  ...  1.000000
9997   WKKPCJY6  ...  0.666667
9998   ST3A265H  ...  1.000000
9999   6Z27IJGD  ...  1.000000
10000  P6190L3Q  ...  0.666667

[10001 rows x 4 columns]

In [101]:
Vac_Train['agreement'].value_counts()

1.000000    5866
0.666667    3894
0.333333     239
Name: agreement, dtype: int64

In [102]:
Vac_Test.columns


Index(['tweet_id', 'safe_text'], dtype='object')

In [103]:
Vac_Train.columns

Index(['tweet_id', 'safe_text', 'label', 'agreement'], dtype='object')

**ONE HOT REPRESENTATION**

In [104]:
# Xtrain


In [105]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [106]:
#DATA CLEANINING


from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [107]:


corpus = []

for i in range(0, len(Xtrain)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', Xtrain['safe_text'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)


Streaming output truncated to the last 5000 lines.
5002
5003
5004
5005
5006
5007
5008
5009
5010
5011
5012
5013
5014
5015
5016
5017
5018
5019
5020
5021
5022
5023
5024
5025
5026
5027
5028
5029
5030
5031
5032
5033
5034
5035
5036
5037
5038
5039
5040
5041
5042
5043
5044
5045
5046
5047
5048
5049
5050
5051
5052
5053
5054
5055
5056
5057
5058
5059
5060
5061
5062
5063
5064
5065
5066
5067
5068
5069
5070
5071
5072
5073
5074
5075
5076
5077
5078
5079
5080
5081
5082
5083
5084
5085
5086
5087
5088
5089
5090
5091
5092
5093
5094
5095
5096
5097
5098
5099
5100
5101
5102
5103
5104
5105
5106
5107
5108
5109
5110
5111
5112
5113
5114
5115
5116
5117
5118
5119
5120
5121
5122
5123
5124
5125
5126
5127
5128
5129
5130
5131
5132
5133
5134
5135
5136
5137
5138
5139
5140
5141
5142
5143
5144
5145
5146
5147
5148
5149
5150
5151
5152
5153
5154
5155
5156
5157
5158
5159
5160
5161
5162
5163
5164
5165
5166
5167
5168
5169
5170
5171
5172
5173
5174
5175
5176
5177
5178
5179
5180
5181
5182
5183
5184
5185
5186
5187
5188
5189
5190
5191

In [108]:
corpus1 = []

for i in range(0, len(Xtest)):
    print(i)
    review1 = re.sub('[^a-zA-Z]', ' ', Xtest['safe_text'][i])
    review1 = review1.lower()
    review1 = review1.split()

    review1 = [ps.stem(word) for word in review1 if not word in stopwords.words('english')]
    review1 = ' '.join(review1)
    corpus1.append(review1)





0


KeyError: ignored

In [68]:
corpus

['amp big homi meanboy meanboy mb mb mmr stegmanlif stegman st url',
 'think devot career prove autism caus vaccin due idiot post seen world autism day',
 'whatcausesaut vaccin vaccin child',
 'mean immun kid someth secretli kill year line trust',
 'thank user catch perform la nuit nyc st ave show start jennifair mmr url',
 'user nearli year old studi mental health studi vaccin rel infanc refut',
 'studi kid find link mmr vaccin autism url',
 'psa vaccin fuck kid',
 'cough extra shuttl everyon think measl vaccinateyourkid',
 'aid vaccin creat oregon health amp scienc univers may clear viru bodi url url',
 'user point text butw bon jovi cover playin alibi hope u come mmr bbq user b',
 'predict vaccin exempt arizona end soon much money lost big pharma',
 'get vaccin china nervou move cheryl southern nevada health district url',
 'mug noch user mmr mixmasterrod dcdj mmr mad hatter url',
 'got influenza vaccin purdu univers student health push user url',
 'sb enrol meningococc diseas pupil

In [70]:
# One hot encoding 
Onehot = [one_hot(words,Vocabulary_size)for words in corpus]
Onehot





[[4521, 3380, 702, 4619, 4619, 1810, 1810, 3429, 3001, 1627, 4048, 1964],
 [1193,
  842,
  1165,
  1665,
  3325,
  1754,
  4487,
  1067,
  974,
  2460,
  670,
  3165,
  3325,
  501],
 [359, 4487, 4487, 2678],
 [2576, 3842, 708, 1873, 1361, 3219, 2689, 4712, 2616],
 [578,
  4726,
  4746,
  1090,
  1879,
  4179,
  2456,
  4048,
  9,
  4024,
  4216,
  2028,
  3429,
  1964],
 [4726, 4541, 2689, 738, 971, 4064, 406, 971, 4487, 4809, 2364, 477],
 [971, 708, 375, 2512, 3429, 4487, 3325, 1964],
 [4523, 4487, 2896, 708],
 [4018, 419, 4681, 3560, 1193, 4875, 3],
 [3696,
  4487,
  1191,
  1406,
  406,
  4521,
  4667,
  329,
  612,
  3517,
  3462,
  4817,
  1964,
  1964],
 [4726,
  1063,
  2833,
  2033,
  4506,
  4529,
  4791,
  2429,
  3390,
  2905,
  4127,
  2196,
  3429,
  3775,
  4726,
  1261],
 [4452, 4487, 3626, 755, 3614, 3273, 1182, 4548, 1044, 3380, 817],
 [683, 4487, 1064, 1743, 2954, 2938, 153, 2521, 406, 1353, 1964],
 [4939, 4448, 4726, 3429, 358, 2137, 3429, 3795, 2356, 1964],
 [2430,

**Embedding Representation**

In [71]:
sent_length = 20
embedded_doc = pad_sequences(Onehot, padding='pre', maxlen= sent_length)
print(embedded_doc)

[[   0    0    0 ... 1627 4048 1964]
 [   0    0    0 ... 3165 3325  501]
 [   0    0    0 ... 4487 4487 2678]
 ...
 [   0    0    0 ... 4791 4726 1065]
 [   0    0    0 ... 2691 4127 1964]
 [   0    0    0 ... 1544  743 1964]]


In [72]:
len(embedded_doc)

10001

**CREATING A MODEL**

In [74]:
embedding_vectors_features = 40
model = Sequential()
model.add(Embedding(Vocabulary_size,embedding_vectors_features, input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss='binary_crossentropy',optimizer = 'adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [75]:
len(embedded_doc),Ytrain.shape

(10001, (10001,))

In [76]:
import numpy as np

x_fin = np.array(embedded_doc)
y_fin = np.array(Ytrain)

In [77]:
x_fin.shape,y_fin.shape

((10001, 20), (10001,))

In [78]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_fin,y_fin, test_size = 0.33, random_state = 42)

**Model Training**

In [80]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10, batch_size=64)

Epoch 1/10
105/105 [==============================] - 4s 37ms/step - loss: nan - accuracy: 0.4900 - val_loss: nan - val_accuracy: 0.4892
Epoch 2/10
105/105 [==============================] - 3s 31ms/step - loss: nan - accuracy: 0.4915 - val_loss: nan - val_accuracy: 0.4892
Epoch 3/10
105/105 [==============================] - 3s 32ms/step - loss: nan - accuracy: 0.4915 - val_loss: nan - val_accuracy: 0.4892
Epoch 4/10
105/105 [==============================] - 3s 32ms/step - loss: nan - accuracy: 0.4915 - val_loss: nan - val_accuracy: 0.4892
Epoch 5/10
105/105 [==============================] - 3s 31ms/step - loss: nan - accuracy: 0.4915 - val_loss: nan - val_accuracy: 0.4892
Epoch 6/10
105/105 [==============================] - 3s 32ms/step - loss: nan - accuracy: 0.4915 - val_loss: nan - val_accuracy: 0.4892
Epoch 7/10
105/105 [==============================] - 3s 33ms/step - loss: nan - accuracy: 0.4915 - val_loss: nan - val_accuracy: 0.4892
Epoch 8/10
105/105 [=====================

In [ ]:
sample_sub = pd.read_csv("/content/drive/My Drive/Colab Notebooks/NLP/vaccinate or not NLP zindi/SampleSubmission.csv")
sample_sub

tweet_id  label
0     00BHHHP1      0
1     00UNMD0E      0
2     01AXPTJF      0
3     01HOEQJW      0
4     01JUKMAO      0
...        ...    ...
5172  ZXVVNC5O      0
5173  ZYIANVI8      0
5174  ZYITEHAH      0
5175  ZZ3BMBTG      0
5176  ZZIYCVNH      0

[5177 rows x 2 columns]